dist: xenial
language: c++
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - iverilog
    - llvm
    - z3

before_install:
  - ls /usr/local/lib
  - ls /usr/local/include/  
  - dpkg -L z3
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip
  - unzip z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip
  - echo $LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04/bin
  - cmake .
  - make -j

script:
  - ./all-tests

compiler:
  - gcc

os:
- linux